### PR TITLE
Mousiplier text

### PR DESCRIPTION
**Pull request by ben-heil**
This PR updates the text of the website to convert mentions of Adage models to mentions of Mousiplier, and updates the "Signatures" terminology to "latent variables"

I haven't been able to test it since my laptop doesn't play nicely with Node. It's all text changes so it *shouldn't* knock over the server, but use caution

### CODE REVIEW

**Comment by vincerubinetti** [comment]
I had to downgrade to Node version 16 for it to run. Could you put a file named `.nvmrc` in the root folder with the contents `v16` (just to indicate that version 16 is required, and to allow a tool called `nvm` to let users use the appropriate version when running locally).

For the `TODO` links, perhaps you just want to leave the `href` blank, and comment out the link all together with a `TODO` comment?

```jsx
        {/* TODO */}
        {/* <div className='altmetric'>
          <div
            data-badge-popover='left'
            data-badge-type='donut'
            data-doi=''
            className='altmetric-embed'
          />
        </div> */}
```

Up to you. It's just that `href="TODO"` will link to the current page plus `/TODO`.

**Review by vincerubinetti — APPROVED** [review]

**Comment by ben-heil** [comment]
Sounds good, I commented out sections where I was using TODO hrefs, and added the nvmrc file

**Comment by vincerubinetti** [comment]
Thanks, looks good, feel free to merge whenever.

**Comment by ben-heil** [comment]
I don't have write permissions in the repo for some reason, can you merge it?

**Pull request merged**
